-- ============================================================
-- HomeServe — Seed the service catalogue
-- Migration: 006_seed_services.sql
-- Idempotent: (category, name) is unique and the insert skips existing rows.
-- Source of truth for the rows is seeds/001_services.sql.
-- ============================================================

ALTER TABLE services ADD CONSTRAINT services_category_name_key UNIQUE (category, name);

INSERT INTO services (category, name, description, base_price, price_unit, min_duration_hours, max_duration_hours, sort_order) VALUES
('Plumbing', 'Tap & Faucet Repair', 'Fix dripping taps, replace faucets, repair washers and seals.', 299, 'fixed', 0.5, 2, 1),
('Plumbing', 'Pipe Leak Repair', 'Locate and fix water pipe leaks — exposed or concealed.', 499, 'fixed', 1, 4, 2),
('Plumbing', 'Bathroom Plumbing Installation', 'Complete plumbing setup for new or renovation bathroom.', 2999, 'fixed', 4, 12, 3),
('Plumbing', 'Water Tank Cleaning', 'Professional cleaning of overhead or underground water tanks.', 799, 'fixed', 2, 5, 4),
('Electrical', 'Switch & Socket Repair', 'Replace or repair switches, sockets, and MCB breakers.', 299, 'fixed', 0.5, 2, 1),
('Electrical', 'Fan Installation', 'Install ceiling fan including wiring and regulator.', 399, 'fixed', 0.5, 1.5, 2),
('Electrical', 'Lighting & Wiring', 'Install light fittings, run new wiring, replace old wiring.', 1499, 'fixed', 2, 8, 3),
('Electrical', 'MCB / DB Board Work', 'Install or repair main distribution board and MCBs.', 1999, 'fixed', 2, 6, 4),
('Carpentry', 'Door Repair & Fitting', 'Fix hinges, handles, locks; adjust sticking doors.', 499, 'fixed', 1, 3, 1),
('Carpentry', 'Window Repair & Fitting', 'Repair window frames, grills, and locks.', 599, 'fixed', 1, 4, 2),
('Carpentry', 'Wardrobe Installation', 'Assemble and install flat-pack or custom wardrobes.', 1499, 'fixed', 3, 8, 3),
('Painting', 'Room Painting (per room)', 'Wall and ceiling painting — prep, primer, and 2 finish coats.', 3999, 'fixed', 4, 12, 1),
('Painting', 'Full Apartment Painting', 'Complete interior painting for 1-4 BHK apartments.', 14999, 'per_sqft', 8, 48, 2),
('Painting', 'Exterior Painting', 'Weather-proof exterior painting for houses and buildings.', 15, 'per_sqft', 8, 48, 3),
('Painting', 'Texture & Stencil Work', 'Decorative texture, stucco, and stencil wall finishes.', 50, 'per_sqft', 4, 24, 4),
('Civil Work', 'Wall Crack & Plaster Repair', 'Repair cracks, patch damaged plaster, skim coat finish.', 1499, 'fixed', 2, 8, 1),
('Civil Work', 'Room Addition / Renovation', 'Civil construction — walls, slabs, columns, brickwork.', 450, 'per_sqft', 40, 480, 2),
('Civil Work', 'Demolition & Debris Removal', 'Safe demolition and complete clean-up.', 2999, 'fixed', 4, 24, 3),
('Interior Design', 'Interior Design Consultation', '2-hour consultation with a certified interior designer.', 1999, 'fixed', 2, 2, 1),
('Interior Design', 'Full Home Interior Design', 'End-to-end design: layouts, materials, supervision.', 150, 'per_sqft', 40, 480, 2),
('Interior Design', '3D Visualisation Package', 'Photorealistic 3D renders for 2-3 rooms.', 7999, 'fixed', 24, 96, 3),
('Modular Kitchen', 'Modular Kitchen Installation', 'Supply and install complete modular kitchen system.', 80000, 'fixed', 16, 80, 1),
('Modular Kitchen', 'Kitchen Cabinet Repair', 'Fix hinges, handles, shutters on existing modular units.', 799, 'fixed', 2, 6, 2),
('Modular Kitchen', 'Countertop Replacement', 'Replace kitchen countertop — granite, quartz, or laminate.', 250, 'per_sqft', 4, 16, 3),
('Home Cleaning', 'Standard Home Cleaning', 'Regular cleaning: sweep, mop, vacuum, bathroom scrub.', 499, 'fixed', 2, 4, 1),
('Home Cleaning', 'Deep Cleaning', 'Full deep clean including kitchen, bathrooms, and all surfaces.', 1499, 'fixed', 4, 8, 2),
('Home Cleaning', 'Move-In / Move-Out Cleaning', 'Thorough clean for empty apartments — ready to occupy.', 1999, 'fixed', 4, 10, 3),
('Home Cleaning', 'Sofa & Carpet Cleaning', 'Professional steam or dry cleaning for upholstery and carpets.', 999, 'fixed', 2, 5, 4),
('Pest Control', 'Cockroach Treatment', 'Gel-bait treatment for cockroach control.', 499, 'fixed', 1, 2, 1),
('Pest Control', 'Termite Treatment', 'Chemical barrier and baiting system for termites.', 2999, 'fixed', 4, 16, 2),
('Pest Control', 'Rodent Control', 'Trapping, sealing entry points, and bait stations.', 1499, 'fixed', 2, 6, 3),
('Pest Control', 'Bed Bug Treatment', 'Heat or chemical treatment for bed bug elimination.', 1999, 'fixed', 3, 8, 4),
('False Ceiling', 'Gypsum False Ceiling', 'Plain or designer gypsum board false ceiling with lighting.', 60, 'per_sqft', 8, 48, 1),
('False Ceiling', 'POP False Ceiling', 'Pop (Plaster of Paris) false ceiling with cornice work.', 55, 'per_sqft', 8, 48, 2),
('False Ceiling', 'False Ceiling Repair', 'Patch and repaint damaged false ceiling sections.', 999, 'fixed', 2, 6, 3),
('Flooring', 'Tile / Marble Flooring', 'Supply and lay ceramic, vitrified, or marble tiles.', 85, 'per_sqft', 8, 48, 1),
('Flooring', 'Wooden / Laminate Flooring', 'Install hardwood, engineered wood, or laminate planks.', 110, 'per_sqft', 4, 24, 2),
('Flooring', 'Flooring Polish & Restoration', 'Polish, grind, and restore existing marble or granite floors.', 15, 'per_sqft', 4, 16, 3),
('Waterproofing', 'Terrace / Roof Waterproofing', 'Waterproof coating for terraces, sunshades, and roofs.', 35, 'per_sqft', 4, 24, 1),
('Waterproofing', 'Bathroom Waterproofing', 'Waterproof membrane for wet areas — floor and walls.', 7999, 'fixed', 4, 16, 2),
('Waterproofing', 'External Wall Waterproofing', 'Seal leaks in external walls and parapet walls.', 40, 'per_sqft', 4, 24, 3),
('AC Repair', 'AC Service (General)', 'Full service: filter clean, gas check, coil wash.', 499, 'fixed', 1, 3, 1),
('AC Repair', 'AC Gas Refilling', 'Top up or replace refrigerant gas for split/window AC.', 1499, 'fixed', 1, 3, 2),
('AC Repair', 'AC Installation / Uninstallation', 'Install or remove split or window AC unit.', 999, 'fixed', 1, 3, 3),
('AC Repair', 'AC PCB / Compressor Repair', 'Diagnose and replace faulty PCB or compressor parts.', 2999, 'fixed', 2, 6, 4),
('Appliance Repair', 'Washing Machine Repair', 'Diagnose and repair all major washing machine issues.', 399, 'fixed', 1, 3, 1),
('Appliance Repair', 'Refrigerator Repair', 'Fix cooling, leaking, compressor, or electrical faults.', 499, 'fixed', 1, 3, 2),
('Appliance Repair', 'Microwave / Oven Repair', 'Repair heating, turntable, electrical and door faults.', 349, 'fixed', 0.5, 2, 3),
('Appliance Repair', 'Geyser / Water Heater Repair', 'Fix heating element, thermostat, and leaks.', 399, 'fixed', 1, 2, 4),
('Deep Cleaning', 'Kitchen Deep Clean', 'Degrease chimney, stove, tiles, cabinets top to bottom.', 1299, 'fixed', 3, 6, 1),
('Deep Cleaning', 'Bathroom Deep Clean', 'Scrub tiles, sanitise fixtures, remove hard-water stains.', 699, 'fixed', 1.5, 3, 2),
('Deep Cleaning', 'Full Apartment Deep Clean', 'Comprehensive deep clean for 1-4 BHK apartments.', 2499, 'fixed', 5, 10, 3),
('Bathroom Remodeling', 'Bathroom Renovation (full)', 'Complete gut-and-redo bathroom renovation.', 35000, 'fixed', 40, 120, 1),
('Bathroom Remodeling', 'Bathroom Fitting (fixtures)', 'Install new WC, basin, shower, bathtub, and accessories.', 9999, 'fixed', 8, 24, 2),
('Kitchen Remodeling', 'Kitchen Renovation (full)', 'Complete kitchen renovation — civil, plumbing, electrical, cabinets.', 75000, 'fixed', 80, 240, 1),
('Kitchen Remodeling', 'Kitchen Backsplash Tiling', 'Tile or stone backsplash installation for kitchen walls.', 60, 'per_sqft', 4, 16, 2),
('CCTV Installation', 'CCTV Camera Installation (4 cameras)', 'Supply, install, and configure 4-camera CCTV system with DVR.', 9999, 'fixed', 4, 8, 1),
('CCTV Installation', 'CCTV System Maintenance', 'Clean lenses, check connections, test recording and alerts.', 999, 'fixed', 1, 3, 2),
('CCTV Installation', 'Video Doorbell Installation', 'Install and configure smart video doorbell.', 1499, 'fixed', 1, 2, 3),
('Solar Installation', 'Solar Panel Installation (1kW)', 'Supply and install 1kW rooftop solar panel system.', 45000, 'fixed', 8, 24, 1),
('Solar Installation', 'Solar System Maintenance', 'Clean panels, check inverter, test output.', 1499, 'fixed', 2, 4, 2),
('Smart Home', 'Smart Lighting Installation', 'Install smart bulbs/switches with app/voice control.', 4999, 'fixed', 3, 8, 1),
('Smart Home', 'Smart Lock Installation', 'Supply and fit digital/smart door lock with app access.', 3999, 'fixed', 1, 3, 2),
('Smart Home', 'Home Automation Consultation', '2-hour smart home planning session with roadmap.', 1999, 'fixed', 2, 2, 3),
('Smart Home', 'Smart Home Full Setup (per room)', 'End-to-end smart home automation per room.', 15000, 'fixed', 8, 32, 4),
('Gardening & Landscaping', 'Garden Maintenance (per visit)', 'Mow, trim, weed, and water garden — per session.', 499, 'fixed', 1, 4, 1),
('Gardening & Landscaping', 'Landscaping Design & Setup', 'Design and install garden with plants, paths, and lighting.', 200, 'per_sqft', 16, 80, 2),
('Gardening & Landscaping', 'Vertical Garden / Balcony Garden', 'Design and install low-maintenance balcony or vertical garden.', 4999, 'fixed', 4, 16, 3),
('Custom Furniture', 'Custom Wardrobe (per unit)', 'Measure, design, and install custom wardrobe.', 12000, 'fixed', 8, 32, 1),
('Custom Furniture', 'Custom Study / TV Unit', 'Design and build custom study desk or TV unit.', 8000, 'fixed', 8, 24, 2),
('Custom Furniture', 'Custom Sofa / Upholstery', 'Bespoke sofa fabrication or re-upholstery of existing pieces.', 15000, 'fixed', 16, 48, 3),
('Custom Furniture', 'Custom Storage Solutions', 'Built-in shelves, cabinets, loft beds — space-optimised.', 7000, 'fixed', 8, 24, 4)
ON CONFLICT (category, name) DO NOTHING;
